# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da27b4530a85ba5917cf476ff91b26dc0dcaeea3de4c5cfa877652547a21e47d8c2aa76637d68f547a2e68d172fc274dd1a8089208da5710e92e0b0fdf27dd3c

test:
  secret_key_base: 171fec372c46b2e42da68da1cea5622472b4c72df73e3ee047370693f876609f3e41427791d40e486d20074d1187106891cf971ace30655e9834962c7a7f57b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
